version: '3.1'

services:
  database:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - './data:/var/lib/mysql:Z'

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 9090:80
    environment:
      - PMA_HOST=database
    depends_on:
      - database
